# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x07monitor\"M\n\rMetricRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63pu\x18\x02 \x01(\x02\x12\x0e\n\x06memory\x18\x03 \x01(\x02\x12\x0c\n\x04\x64isk\x18\x04 \x01(\x02\"!\n\x0eMetricResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0c\x41\x64minRequest\"a\n\x0c\x44\x65viceStatus\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63pu\x18\x02 \x01(\x02\x12\x0e\n\x06memory\x18\x03 \x01(\x02\x12\x0c\n\x04\x64isk\x18\x04 \x01(\x02\x12\x13\n\x0blast_update\x18\x05 \x01(\t\">\n\x14SystemStatusResponse\x12&\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x15.monitor.DeviceStatus2\xa0\x01\n\rMetricService\x12\x44\n\rStreamMetrics\x12\x16.monitor.MetricRequest\x1a\x17.monitor.MetricResponse(\x01\x30\x01\x12I\n\x0fWatchAllDevices\x12\x15.monitor.AdminRequest\x1a\x1d.monitor.SystemStatusResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICREQUEST']._serialized_start=26
  _globals['_METRICREQUEST']._serialized_end=103
  _globals['_METRICRESPONSE']._serialized_start=105
  _globals['_METRICRESPONSE']._serialized_end=138
  _globals['_ADMINREQUEST']._serialized_start=140
  _globals['_ADMINREQUEST']._serialized_end=154
  _globals['_DEVICESTATUS']._serialized_start=156
  _globals['_DEVICESTATUS']._serialized_end=253
  _globals['_SYSTEMSTATUSRESPONSE']._serialized_start=255
  _globals['_SYSTEMSTATUSRESPONSE']._serialized_end=317
  _globals['_METRICSERVICE']._serialized_start=320
  _globals['_METRICSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
